version: "3.8"

services:
  web:
    build: .
    environment:
      RAILS_ENV: "development"
      DATABASE_URL: "postgresql://postgres:password@db/api_model_development"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata:/var/lib/postgresql/data/

volumes:
  dbdata: