version: "3.8"

services:
  web:
    build: .
#    command: "db:setup && db:migrate && db:seed"
#    image: api_model_image:latest
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db
      DBHOST: localhost
      DBUSER: api_model
      DBPASS: password
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: api_model_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata:/var/lib/postgresql/data/

volumes:
  dbdata: